### ISSUE TITLE
Zipcode.find_by_city_state Error

### ISSUE THREAD

**Issue by akoinesjr** [midwire/my_zipcode_gem#19]
FYI running  `Zipcode.find_by_city_state "Shawnee Mission", "KS"`

As shown in the documentation produces the following:

```
  Zipcode Load (2.2ms)  SELECT  "zipcodes".* FROM "zipcodes" WHERE (city like 'Shawnee Mission%' AND states.abbr like '%KS%') ORDER BY "zipcodes"."id" ASC LIMIT $1  [["LIMIT", 1]]
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "states"
LINE 1: ...zipcodes" WHERE (city like 'Shawnee Mission%' AND states.abb...
                                                             ^
: SELECT  "zipcodes".* FROM "zipcodes" WHERE (city like 'Shawnee Mission%' AND states.abbr like '%KS%') ORDER BY "zipcodes"."id" ASC LIMIT $1
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:587:in `execute_and_clear'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/querying.rb:39:in `find_by_sql'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation.rb:706:in `exec_queries'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation.rb:583:in `load'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation.rb:260:in `records'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation.rb:256:in `to_a'
... 7 levels...
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
	from /Users/andrew/Development/innovation_quotient/iq_alpha/bin/rails:9:in `<top (required)>'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

I have not yet dug into this as I was able to achieve the desired result with 

`Zipcode.find_by_city_and_state_id($CITY,$STATE_ID)`

**Comment by cmckni3** [comment]
This is an issue with queries being explicit in ActiveRecord 4+. I'll get it fixed up shortly.

**Comment by akoinesjr** [comment]
Gotcha. Thanks for replying quickly despite this being such a minor issue 👍 

Relatedly, I see in the docs that the `find_by_city_state` is intended to be used to find one zip code that corresponds to a city.

Maybe a `find_all_by_city_state` would also be useful? It's relevant for my use case at least.
